-- ===========================================================================
-- Masarat Site Attendance — PostgreSQL schema
-- Ported from server/schema.sql (SQLite) for Supabase Postgres.
--
-- PORTING RULES APPLIED (deliberate, to keep application behaviour identical):
--
--   INTEGER PRIMARY KEY AUTOINCREMENT
--       -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--          "BY DEFAULT" (not ALWAYS) so explicit id inserts still work, as in SQLite.
--
--   REAL -> DOUBLE PRECISION
--          NOT Postgres REAL. Postgres REAL is 4-byte (~7 significant digits),
--          which is marginal for latitude/longitude at 5 decimal places.
--          SQLite REAL is already 8-byte, so DOUBLE PRECISION is the faithful port.
--
--   TEXT -> TEXT (unchanged)
--          All dates stay 'YYYY-MM-DD' TEXT and all timestamps stay ISO-8601 UTC
--          TEXT. This is deliberate: every date comparison in the application is
--          lexicographic on these strings, and it behaves identically in Postgres.
--          Converting to DATE/TIMESTAMPTZ would change timezone semantics in a
--          system whose whole point is a fixed company-local offset. Do not "fix" this.
--
--   INTEGER flags (0/1) -> INTEGER (NOT boolean)
--          must_change_password, active, crosses_midnight stay integers so the
--          application's existing 0/1 logic is untouched.
--
--   PRAGMA journal_mode / foreign_keys -> removed
--          Postgres is always durable and always enforces foreign keys.
--
--   UNIQUE with a nullable column: SQLite treats NULLs as distinct; Postgres does
--          too by default (NULLS DISTINCT). attendance(user_id, work_date, shift_id)
--          therefore behaves the same when shift_id IS NULL.
--
-- NEW: login_attempts — the login throttle was an in-memory Map, which cannot work
--      across serverless invocations. It is now shared state in the database.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code TEXT    NOT NULL UNIQUE,
  full_name     TEXT    NOT NULL,
  email         TEXT    NOT NULL UNIQUE,
  phone         TEXT,
  job_title     TEXT,
  department    TEXT,
  role          TEXT    NOT NULL DEFAULT 'employee' CHECK (role IN ('admin', 'supervisor', 'employee')),
  manager_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,  -- المدير المباشر
  password_hash TEXT    NOT NULL,
  must_change_password INTEGER NOT NULL DEFAULT 1,
  active        INTEGER NOT NULL DEFAULT 1,
  -- Per-employee overrides, both additive and both defaulting to "no change
  -- from today's behaviour": NULL follows the app-wide SELFIE_MODE setting,
  -- and 0 keeps the employee restricted to their assigned shift's time window.
  photo_policy   TEXT    CHECK (photo_policy IS NULL OR photo_policy IN ('off', 'optional', 'required')),
  flexible_punch INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT    NOT NULL,
  updated_at    TEXT    NOT NULL
);

-- A project / site the company is contracted on. The geofence lives here.
CREATE TABLE IF NOT EXISTS projects (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       TEXT    NOT NULL UNIQUE,
  name       TEXT    NOT NULL,
  client     TEXT,
  address    TEXT,
  lat        DOUBLE PRECISION NOT NULL,
  lng        DOUBLE PRECISION NOT NULL,
  radius_m   INTEGER NOT NULL DEFAULT 150,
  active     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    NOT NULL,
  updated_at TEXT    NOT NULL
);

-- Restricts which sites an employee may pick. If an employee has zero rows
-- here, every active project is offered to them.
CREATE TABLE IF NOT EXISTS project_members (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  PRIMARY KEY (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS shifts (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          TEXT    NOT NULL UNIQUE,
  name          TEXT    NOT NULL,
  start_time    TEXT    NOT NULL,            -- 'HH:MM' company-local
  end_time      TEXT    NOT NULL,            -- 'HH:MM' company-local
  crosses_midnight INTEGER NOT NULL DEFAULT 0,
  grace_in_min  INTEGER NOT NULL DEFAULT 15, -- minutes after start still "on time"
  grace_out_min INTEGER NOT NULL DEFAULT 10, -- minutes before end still a full shift
  early_in_min  INTEGER NOT NULL DEFAULT 60, -- how early check-in opens
  break_min     INTEGER NOT NULL DEFAULT 0,  -- unpaid break deducted from total
  active        INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS holidays (
  holiday_date TEXT PRIMARY KEY,             -- YYYY-MM-DD
  name         TEXT NOT NULL
);

-- The working calendar: one row per employee per day.
CREATE TABLE IF NOT EXISTS schedules (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  work_date  TEXT    NOT NULL,               -- YYYY-MM-DD
  shift_id   INTEGER REFERENCES shifts(id),
  project_id INTEGER REFERENCES projects(id),
  status     TEXT    NOT NULL DEFAULT 'work'
             CHECK (status IN ('work', 'off', 'leave', 'holiday')),
  note       TEXT,
  created_at TEXT    NOT NULL,
  UNIQUE (user_id, work_date)
);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(work_date);

CREATE TABLE IF NOT EXISTS attendance (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  work_date   TEXT    NOT NULL,              -- shift's calendar day, not the wall date
  shift_id    INTEGER REFERENCES shifts(id),
  project_id  INTEGER NOT NULL REFERENCES projects(id),

  check_in_at        TEXT NOT NULL,          -- server UTC
  check_in_lat       DOUBLE PRECISION NOT NULL,
  check_in_lng       DOUBLE PRECISION NOT NULL,
  check_in_accuracy  DOUBLE PRECISION,
  check_in_distance_m DOUBLE PRECISION,
  check_in_device    TEXT,
  check_in_note      TEXT,
  check_in_photo     TEXT,                   -- object key in the storage bucket

  check_out_at        TEXT,
  check_out_lat       DOUBLE PRECISION,
  check_out_lng       DOUBLE PRECISION,
  check_out_accuracy  DOUBLE PRECISION,
  check_out_distance_m DOUBLE PRECISION,
  check_out_device    TEXT,
  check_out_note      TEXT,
  check_out_photo     TEXT,
  check_out_project_id INTEGER REFERENCES projects(id),

  worked_minutes INTEGER,
  late_minutes   INTEGER NOT NULL DEFAULT 0,
  early_out_minutes INTEGER NOT NULL DEFAULT 0,
  overtime_minutes  INTEGER NOT NULL DEFAULT 0,

  status  TEXT NOT NULL DEFAULT 'open'
          CHECK (status IN ('open', 'closed', 'auto_closed')),
  flags   TEXT NOT NULL DEFAULT '[]',        -- JSON array of review flags
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (user_id, work_date, shift_id)
);
CREATE INDEX IF NOT EXISTS idx_att_user_date ON attendance(user_id, work_date);
CREATE INDEX IF NOT EXISTS idx_att_date ON attendance(work_date);
CREATE INDEX IF NOT EXISTS idx_att_status ON attendance(status);

-- Leave requests. Approving one writes 'leave' days into the schedule, so the
-- roster and the employee's calendar agree without anyone retyping dates.
CREATE TABLE IF NOT EXISTS leave_requests (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type    TEXT    NOT NULL DEFAULT 'annual'
                CHECK (leave_type IN ('annual', 'sick', 'unpaid', 'emergency')),
  from_date     TEXT    NOT NULL,            -- YYYY-MM-DD
  to_date       TEXT    NOT NULL,            -- YYYY-MM-DD, inclusive
  days          INTEGER NOT NULL,
  reason        TEXT,
  status        TEXT    NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
  decided_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  decided_at    TEXT,
  decision_note TEXT,
  created_at    TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_leave_user ON leave_requests(user_id, from_date);
CREATE INDEX IF NOT EXISTS idx_leave_status ON leave_requests(status);

-- Every rejected or accepted punch attempt, for audit and dispute resolution.
CREATE TABLE IF NOT EXISTS punch_log (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  kind       TEXT NOT NULL,                  -- 'in' | 'out'
  outcome    TEXT NOT NULL,                  -- 'accepted' | 'rejected'
  reason     TEXT,
  project_id INTEGER,
  lat        DOUBLE PRECISION,
  lng        DOUBLE PRECISION,
  accuracy   DOUBLE PRECISION,
  distance_m DOUBLE PRECISION,
  device_time TEXT,
  server_time TEXT NOT NULL,
  user_agent TEXT,
  ip         TEXT
);
CREATE INDEX IF NOT EXISTS idx_punchlog_user ON punch_log(user_id, server_time);

-- ---------------------------------------------------------------------------
-- NEW TABLE (not in the SQLite schema)
--
-- The login brute-force throttle used to be an in-memory Map in server/lib/auth.js.
-- On a serverless runtime there is no shared memory between invocations, so the
-- throttle has to live in the database or it does not exist at all.
-- 8 failed attempts per (ip + identifier) per 15 minutes, same as before.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS login_attempts (
  attempt_key TEXT PRIMARY KEY,              -- '<ip>|<lowercased identifier>'
  first_at    TEXT NOT NULL,                 -- ISO-8601 UTC of the window start
  attempts    INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_first ON login_attempts(first_at);
