-- Backs the 60-day selfie cleanup feature (owner's request: "auto free up
-- space every 60 days (make sure first you extracted all data copy to admin
-- firstly)"). A zip of every selfie a cleanup run is about to delete is
-- written here in the SAME run, before any photo is actually removed, so
-- there is always a downloadable copy in the admin console. This is
-- deliberately not Supabase Storage and not email — see api/lib/photoCleanup.ts
-- and db/schema.postgres.sql for the full rationale.
--
-- Only selfie bytes are ever touched by this feature. Attendance records,
-- worked hours and every report stay exactly as they were, forever.
CREATE TABLE IF NOT EXISTS photo_backups (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TEXT    NOT NULL,
  cutoff_at   TEXT    NOT NULL,
  photo_count INTEGER NOT NULL,
  size_bytes  INTEGER NOT NULL,
  archive     BYTEA   NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_photo_backups_created ON photo_backups(created_at);
