-- Supports "check out, come back later, keep the same shift running": each
-- individual check-in/out pair for one attendance row (one user/day/shift) is
-- now recorded as its own session. attendance.check_in_at stays the FIRST
-- session's check-in (late_minutes keeps meaning what it always meant);
-- attendance.check_out_at becomes the MOST RECENT session's check-out;
-- attendance.worked_minutes becomes the sum of every session's own minutes,
-- with the shift's unpaid break deducted once — identical to the old formula
-- when there is exactly one session, so nothing changes for the common case.
CREATE TABLE IF NOT EXISTS attendance_sessions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id INTEGER NOT NULL REFERENCES attendance(id) ON DELETE CASCADE,
  seq         INTEGER NOT NULL,             -- 1, 2, 3... in check-in order for this attendance row

  check_in_at         TEXT NOT NULL,
  check_in_lat        DOUBLE PRECISION NOT NULL,
  check_in_lng        DOUBLE PRECISION NOT NULL,
  check_in_accuracy   DOUBLE PRECISION,
  check_in_distance_m DOUBLE PRECISION,
  check_in_device     TEXT,
  check_in_note       TEXT,
  check_in_photo      TEXT,

  check_out_at         TEXT,
  check_out_lat        DOUBLE PRECISION,
  check_out_lng        DOUBLE PRECISION,
  check_out_accuracy   DOUBLE PRECISION,
  check_out_distance_m DOUBLE PRECISION,
  check_out_device     TEXT,
  check_out_note       TEXT,
  check_out_photo      TEXT,
  check_out_project_id INTEGER REFERENCES projects(id),

  worked_minutes INTEGER,                   -- this session's own minutes, before the shift break is deducted
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (attendance_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_att_sessions_attendance ON attendance_sessions(attendance_id);
